# Generated by Django 3.2.18 on 2023-04-29 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('spot_id', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('result_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.result')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.IntegerField(default=0)),
                ('satisfaction', models.IntegerField(default=0)),
                ('influence', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='number',
            new_name='num',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='developer',
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
        migrations.AddField(
            model_name='choice',
            name='result_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.result'),
        ),
    ]
