# Generated by Django 3.2.18 on 2023-05-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='traveler_id',
        ),
        migrations.AddField(
            model_name='choice',
            name='category',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traveler',
            name='personality',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
