# Generated by Django 3.2.19 on 2023-05-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230509_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
