# Generated by Django 3.2.19 on 2023-05-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_traveler_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveler',
            name='count',
        ),
        migrations.AddField(
            model_name='traveler',
            name='modifier',
            field=models.CharField(default='x', max_length=50),
            preserve_default=False,
        ),
    ]
