# Generated by Django 3.2.19 on 2023-05-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_traveler_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveler',
            name='content',
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='modifier',
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='personality',
        ),
        migrations.AddField(
            model_name='traveler',
            name='data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Spot',
        ),
    ]
