# Generated by Django 3.2.19 on 2023-05-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230527_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
