# Generated by Django 3.2.19 on 2023-06-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_survey_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.JSONField(),
        ),
    ]
