# Generated by Django 3.2.19 on 2023-06-05 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_question_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='content',
            new_name='data',
        ),
    ]
