# Generated by Django 3.2.19 on 2023-06-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_content_question_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='data',
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
