# Generated by Django 3.2.19 on 2023-06-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20230605_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='data',
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
